services:
  - type: web
    name: weatherAppFrontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn weatherAppFrontend.wsgi --log-file -
    
